/* ============================================
   GENERATOR PAGE - INTERACTIVE FEATURES
   AI Islamic Content Generator
   ============================================ */

// Sirf generator page pe chale
if (document.querySelector('.generator-page')) {
  
  // ---------- 1. TYPE BUTTONS (Content Type) ----------
  const typeButtons = document.querySelectorAll('.type-btn');
  let selectedType = 'quran';
  
  typeButtons.forEach(btn => {
    btn.addEventListener('click', () => {
      typeButtons.forEach(b => b.classList.remove('active'));
      btn.classList.add('active');
      selectedType = btn.dataset.type;
      console.log('✅ Content type:', selectedType);
    });
  });
  
  // ---------- 2. LANGUAGE OPTIONS ----------
  const langOptions = document.querySelectorAll('.lang-option');
  let selectedLang = 'ur';
  
  langOptions.forEach(btn => {
    btn.addEventListener('click', () => {
      langOptions.forEach(b => b.classList.remove('active'));
      btn.classList.add('active');
      selectedLang = btn.dataset.lang;
      console.log('✅ Language:', selectedLang);
    });
  });
  
  // ---------- 3. LENGTH OPTIONS ----------
  const lengthOptions = document.querySelectorAll('.length-option');
  let selectedLength = 'medium';
  
  lengthOptions.forEach(btn => {
    btn.addEventListener('click', () => {
      lengthOptions.forEach(b => b.classList.remove('active'));
      btn.classList.add('active');
      selectedLength = btn.dataset.length;
      console.log('✅ Length:', selectedLength);
    });
  });
  
  // ---------- 4. SUGGESTION CHIPS ----------
  const suggestionChips = document.querySelectorAll('.suggestion-chip');
  const topicInput = document.getElementById('topicInput');
  
  suggestionChips.forEach(chip => {
    chip.addEventListener('click', () => {
      if (topicInput) {
        topicInput.value = chip.dataset.topic;
        topicInput.focus();
        console.log('✅ Suggestion applied:', chip.dataset.topic);
      }
    });
  });
  
  // ---------- 5. GENERATE BUTTON ----------
  const generateBtn = document.getElementById('generateBtn');
  const outputEmpty = document.getElementById('outputEmpty');
  const outputLoading = document.getElementById('outputLoading');
  const outputResult = document.getElementById('outputResult');
  const outputError = document.getElementById('outputError');
  const resultContent = document.getElementById('resultContent');
  const resultTime = document.getElementById('resultTime');
  const errorMessage = document.getElementById('errorMessage');
  
  function showState(state) {
    [outputEmpty, outputLoading, outputResult, outputError].forEach(el => {
      if (el) el.style.display = 'none';
    });
    
    if (state === 'empty' && outputEmpty) outputEmpty.style.display = 'flex';
    if (state === 'loading' && outputLoading) outputLoading.style.display = 'flex';
    if (state === 'result' && outputResult) outputResult.style.display = 'flex';
    if (state === 'error' && outputError) outputError.style.display = 'flex';
  }
  
    if (generateBtn) {
    generateBtn.addEventListener('click', async () => {
      
      const topic = topicInput ? topicInput.value.trim() : '';
      
      if (!topic) {
        alert('⚠️ برائے مہربانی موضوع لکھیں');
        topicInput.focus();
        return;
      }
      
      showState('loading');
      
      console.log('🚀 Sending request to Gemini AI...');
      console.log('   Topic:', topic);
      console.log('   Type:', selectedType);
      console.log('   Language:', selectedLang);
      console.log('   Length:', selectedLength);
      
      try {
        // Call serverless function
        const response = await fetch('/api/generate', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json'
          },
          body: JSON.stringify({
            topic: topic,
            type: selectedType,
            language: selectedLang,
            length: selectedLength
          })
        });
        
        const data = await response.json();
        
        if (!response.ok || !data.success) {
          throw new Error(data.message || data.error || 'کچھ غلط ہو گیا');
        }
        
        // Show result
        if (resultContent) {
          resultContent.textContent = data.content;
        }
        
        if (resultTime) {
          const now = new Date();
          resultTime.textContent = now.toLocaleTimeString('ur-PK', { 
            hour: '2-digit', 
            minute: '2-digit' 
          });
        }
        
        showState('result');
        console.log('✅ Content generated by Gemini AI!');
        
      } catch (error) {
        console.error('❌ Generation failed:', error);
        
        if (errorMessage) {
          errorMessage.textContent = error.message || 'دوبارہ کوشش کریں';
        }
        
        showState('error');
      }
      
    });
  }
  
  // ---------- 6. DEMO CONTENT GENERATOR ----------
  function generateDemoContent(topic, type, lang, length) {
    const bismillah = 'بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ';
    
    const typeTitles = {
      quran: '📖 قرآن کی روشنی میں',
      hadith: '🕌 احادیث مبارکہ کی روشنی میں',
      bayan: '✍️ بیان و خطبہ',
      post: '📱 سوشل میڈیا پوسٹ',
      quote: '💬 اسلامی اقوال',
      dua: '🤲 دعائیں و اذکار'
    };
    
    const title = typeTitles[type] || 'اسلامی مواد';
    
    return `${bismillah}

${title}

الموضوع: ${topic}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━

✨ یہ ایک نمونہ (DEMO) مواد ہے۔

آپ نے درج ذیل تفصیلات منتخب کی ہیں:

📌 موضوع: ${topic}
📋 قسم: ${type}
🌐 زبان: ${lang}
📏 لمبائی: ${length}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━

🔧 اگلے قدم میں Gemini AI کی مکمل integration ہوگی، 
جس کے بعد یہاں اصل اسلامی مواد تیار ہوگا۔

ان شاء اللہ، بہت جلد آپ مکمل AI کی طاقت استعمال کر سکیں گے۔

━━━━━━━━━━━━━━━━━━━━━━━━━━━━

جزاک الله خیراً`;
  }
  
  // ---------- 7. ACTION BUTTONS (Copy, Download, Share, Regen) ----------
  
  // Copy Button
  const copyBtn = document.getElementById('copyBtn');
  if (copyBtn) {
    copyBtn.addEventListener('click', async () => {
      const content = resultContent ? resultContent.textContent : '';
      
      if (!content) {
        alert('⚠️ پہلے مواد بنائیں');
        return;
      }
      
      try {
        await navigator.clipboard.writeText(content);
        
        // Success feedback
        const originalHTML = copyBtn.innerHTML;
        copyBtn.innerHTML = '<i class="fas fa-check"></i><span>ہو گیا!</span>';
        copyBtn.style.background = 'linear-gradient(135deg, #10B981, #059669)';
        copyBtn.style.color = 'white';
        
        setTimeout(() => {
          copyBtn.innerHTML = originalHTML;
          copyBtn.style.background = '';
          copyBtn.style.color = '';
        }, 2000);
        
        console.log('✅ Copied to clipboard');
        
      } catch (err) {
        alert('❌ کاپی نہیں ہو سکا');
        console.error(err);
      }
    });
  }
  
  // Download Button
  const downloadBtn = document.getElementById('downloadBtn');
  if (downloadBtn) {
    downloadBtn.addEventListener('click', () => {
      const content = resultContent ? resultContent.textContent : '';
      
      if (!content) {
        alert('⚠️ پہلے مواد بنائیں');
        return;
      }
      
      const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `islamic-content-${Date.now()}.txt`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
      
      console.log('✅ Downloaded');
    });
  }
  
  // Share Button
  const shareBtn = document.getElementById('shareBtn');
  if (shareBtn) {
    shareBtn.addEventListener('click', async () => {
      const content = resultContent ? resultContent.textContent : '';
      
      if (!content) {
        alert('⚠️ پہلے مواد بنائیں');
        return;
      }
      
      if (navigator.share) {
        try {
          await navigator.share({
            title: 'Islamic AI Content',
            text: content
          });
          console.log('✅ Shared');
        } catch (err) {
          if (err.name !== 'AbortError') {
            console.error('Share failed:', err);
          }
        }
      } else {
        // Fallback: Copy to clipboard
        await navigator.clipboard.writeText(content);
        alert('✅ مواد کاپی ہو گیا! اب آپ جہاں چاہیں پیسٹ کر سکتے ہیں');
      }
    });
  }
  
  // Regenerate Button
  const regenBtn = document.getElementById('regenBtn');
  if (regenBtn) {
    regenBtn.addEventListener('click', () => {
      if (generateBtn) generateBtn.click();
    });
  }
  
  console.log('✨ Generator Page — Interactive features loaded!');
}